import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { formatDate } from "@/lib/dates";
import { Section, EmptyState, MockAiNote, buttonSecondaryClass } from "@/components/ui";
import { SubmitButton } from "@/components/SubmitButton";
import { CopyButton } from "@/components/CopyButton";
import { generatePoster } from "./actions";

export default async function PosterPage({ params }: PageProps<"/projects/[id]/poster">) {
  const { id } = await params;
  const project = await db.project.findUnique({
    where: { id },
    select: {
      id: true,
      songTitle: true,
      kpopGroup: true,
      themeVibe: true,
      dateWindowLabel: true,
      posterSvg: true,
      posterUpdatedAt: true,
      posterVariant: true,
    },
  });
  if (!project) notFound();

  return (
    <>
      <Section
        title="Recruitment poster"
        description="Generated from the song name, group, theme and date window. Aimed at recruiting 4–8 dancers with a vague date window. Regenerate cycles through 4 layouts."
        actions={
          <form action={generatePoster.bind(null, project.id)}>
            <SubmitButton pendingText="Generating…">
              {project.posterSvg ? "Regenerate (next layout)" : "Generate poster"}
            </SubmitButton>
          </form>
        }
      >
        {!project.themeVibe || !project.dateWindowLabel ? (
          <p className="mb-3 text-xs text-[var(--warn)]">
            Tip: set a theme/vibe and a date window on the Overview tab for a better poster.
          </p>
        ) : null}

        {project.posterSvg ? (
          <div className="space-y-3">
            <div
              className="mx-auto max-w-sm overflow-hidden rounded-xl border border-border bg-white"
              // The SVG is generated by our own template code in src/lib/ai/poster.ts.
              dangerouslySetInnerHTML={{ __html: project.posterSvg }}
            />
            <div className="flex flex-wrap items-center gap-2">
              <a
                href={`/projects/${project.id}/poster/svg`}
                target="_blank"
                rel="noreferrer"
                className={buttonSecondaryClass}
              >
                Open SVG in new tab
              </a>
              <CopyButton text={project.posterSvg} label="Copy SVG markup" />
              {project.posterUpdatedAt ? (
                <span className="text-xs text-muted">
                  Layout {project.posterVariant + 1} of 4 · generated{" "}
                  {formatDate(project.posterUpdatedAt)}
                </span>
              ) : null}
            </div>
          </div>
        ) : (
          <EmptyState>No poster yet. Hit &ldquo;Generate poster&rdquo;.</EmptyState>
        )}

        <MockAiNote what="The poster is real (a templated SVG in the brand palette + font), but the tagline" />
        <p className="mt-1 text-xs text-muted">
          Free image generation isn&rsquo;t possible without a paid API, so there&rsquo;s no
          photo/illustration background yet — see the note in{" "}
          <code>src/lib/ai/poster.ts</code>.
        </p>
      </Section>
    </>
  );
}
