// Small presentational building blocks. All server-safe (no hooks).
import Link from "next/link";
import type { ReactNode } from "react";

export const buttonClass =
  "inline-flex items-center justify-center gap-1.5 rounded-lg bg-accent px-3.5 py-2 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-[var(--periwinkle-strong)] disabled:opacity-50";

export const buttonSecondaryClass =
  "inline-flex items-center justify-center gap-1.5 rounded-lg border border-border bg-surface px-3.5 py-2 text-sm font-semibold text-foreground transition-colors hover:bg-accent-soft disabled:opacity-50";

export const buttonDangerClass =
  "inline-flex items-center justify-center gap-1.5 rounded-lg bg-[var(--bad-soft)] px-3 py-1.5 text-sm font-semibold text-[var(--bad)] transition-colors hover:brightness-95 disabled:opacity-50";

export function PageHeader({
  title,
  description,
  actions,
  breadcrumb,
}: {
  title: string;
  description?: ReactNode;
  actions?: ReactNode;
  breadcrumb?: ReactNode;
}) {
  return (
    <div className="mb-6">
      {breadcrumb ? (
        <div className="mb-1.5 text-sm text-muted">{breadcrumb}</div>
      ) : null}
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-[1.7rem] leading-tight text-ink">{title}</h1>
          {description ? (
            <p className="mt-1.5 max-w-2xl text-sm text-muted">{description}</p>
          ) : null}
        </div>
        {actions ? <div className="flex gap-2">{actions}</div> : null}
      </div>
    </div>
  );
}

export function Section({
  title,
  description,
  actions,
  children,
}: {
  title?: string;
  description?: ReactNode;
  actions?: ReactNode;
  children: ReactNode;
}) {
  return (
    <section className="mb-6 rounded-2xl border border-border bg-surface p-5 shadow-[0_1px_2px_rgba(44,53,71,0.04),0_8px_24px_-12px_rgba(44,53,71,0.10)]">
      {(title || actions) && (
        <div className="mb-3 flex flex-wrap items-start justify-between gap-2">
          <div>
            {title ? (
              <h2 className="text-lg text-ink">{title}</h2>
            ) : null}
            {description ? (
              <p className="mt-0.5 text-sm text-muted">{description}</p>
            ) : null}
          </div>
          {actions}
        </div>
      )}
      {children}
    </section>
  );
}

type Tone = "neutral" | "accent" | "good" | "bad" | "warn";

const toneClass: Record<Tone, string> = {
  neutral: "bg-ice-tint text-muted border-border",
  accent: "bg-accent-soft text-[var(--periwinkle-strong)] border-transparent",
  good: "bg-[var(--good-soft)] text-[var(--good)] border-transparent",
  bad: "bg-[var(--bad-soft)] text-[var(--bad)] border-transparent",
  warn: "bg-[var(--warn-soft)] text-[var(--warn)] border-transparent",
};

export function Badge({
  children,
  tone = "neutral",
}: {
  children: ReactNode;
  tone?: Tone;
}) {
  return (
    <span
      className={`inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium ${toneClass[tone]}`}
    >
      {children}
    </span>
  );
}

export function SampleDataBadge() {
  return <Badge tone="warn">SAMPLE DATA</Badge>;
}

export function MockAiNote({ what }: { what: string }) {
  return (
    <p className="mt-2 rounded-lg border border-[var(--warn-soft)] bg-[var(--warn-soft)] px-3 py-2 text-xs text-[var(--warn)]">
      <strong>Sample AI output.</strong> {what} is generated by a placeholder in{" "}
      <code>src/lib/ai/</code>, not a real model yet. See{" "}
      <span className="font-mono">README → &ldquo;Wiring in real AI&rdquo;</span>.
    </p>
  );
}

export function EmptyState({ children }: { children: ReactNode }) {
  return (
    <div className="rounded-xl border border-dashed border-border bg-ice-tint p-6 text-center text-sm text-muted">
      {children}
    </div>
  );
}

export function Field({
  label,
  htmlFor,
  hint,
  children,
}: {
  label: string;
  htmlFor?: string;
  hint?: ReactNode;
  children: ReactNode;
}) {
  return (
    <div>
      <label htmlFor={htmlFor}>{label}</label>
      {children}
      {hint ? <p className="mt-1 text-xs text-muted normal-case">{hint}</p> : null}
    </div>
  );
}

export function LinkButton({
  href,
  children,
  variant = "primary",
}: {
  href: string;
  children: ReactNode;
  variant?: "primary" | "secondary";
}) {
  return (
    <Link
      href={href}
      className={variant === "primary" ? buttonClass : buttonSecondaryClass}
    >
      {children}
    </Link>
  );
}

/** Frost hero band with the cropped channel banner behind a legibility gradient. */
export function Hero({
  title,
  children,
  image = "/brand/hero.jpg",
}: {
  title: ReactNode;
  children?: ReactNode;
  image?: string;
}) {
  return (
    <div className="relative mb-8 overflow-hidden rounded-2xl border border-border">
      <div
        className="absolute inset-0 bg-cover bg-center"
        style={{ backgroundImage: `url(${image})` }}
        aria-hidden
      />
      <div
        className="absolute inset-0"
        style={{
          background:
            "linear-gradient(100deg, rgba(244,246,250,0.99) 0%, rgba(244,246,250,0.97) 46%, rgba(240,243,248,0.86) 74%, rgba(238,241,247,0.62) 100%)",
        }}
        aria-hidden
      />
      <div className="relative max-w-xl px-6 py-10 sm:px-9 sm:py-12">
        <h1 className="text-3xl text-ink sm:text-[2.5rem] sm:leading-[1.1]">{title}</h1>
        {children ? (
          <div className="mt-2 text-sm text-ink-soft sm:text-base">{children}</div>
        ) : null}
      </div>
    </div>
  );
}
